version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetdb
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend # Utilisation du Dockerfile du backend
    container_name: backend_container
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: projetdb
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    image: nginx:alpine # Utilisation de l'image Nginx
    container_name: frontend_container
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html # Associer le frontend à Nginx
      - ./nginx/nginx.conf:/etc/nginx/default.conf # Monter le bon fichier de configuration
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    depends_on:
      - database
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: